### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by Irshaadv** [liamcain/search-from-directory#1]
Hey Liam, 

This plugin looks like exactly the thing I need for my obsidian setup! But I have no idea how to install and test it (which file do I put where!). Can you please provide some guidance? 

Would very much appreciate the help. 

Best, 
Irshaad

**Comment by liamcain** [comment]
Hi, sorry for taking a while to comb through my Github issues.

- You can install this plugin manually by downloading the files in the latest release: <https://github.com/liamcain/search-from-directory/releases/tag/0.0.3> 
- Or, if you're not comfortable with that, you can use the BRAT plugin to install it: https://github.com/TfTHacker/obsidian42-brat. Just add it as a BETA plugin and it should work as expected.

I'll do my best to add some instructions to the README at some point. LMK if you run into any issues!
